### ISSUE TITLE
undefined symbol (CentOS 6.5)

### ISSUE THREAD

**Issue by ysshin34** [aidanhs/tcldis#2]
[genesis@localhost ~/tcldis-master]$ make TCLCONFIG=/usr/lib64/tclConfig.sh
test -f /usr/lib64/tclConfig.sh
gcc -fPIC -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro,-z,now -fno-strict-overflow -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow -Wstrict-prototypes -Wno-unused-parameter -O2 -DPY_LIBFILE='"libpython2.6.so"' -I/usr/include/python2.6 -I/usr/include/python2.6 -I/usr/include -I/usr/include/tcl-private/unix -I/usr/include/tcl-private/generic -c src/tcldis.c -o _tcldis.o
In file included from /usr/include/tcl-private/generic/tclCompile.h:18,
                 from src/tcldis.c:3:
/usr/include/tcl-private/generic/tclInt.h:2600: warning: function declaration isn’t a prototype
src/tcldis.c: In function ‘getBcTclObj’:
src/tcldis.c:46: warning: passing argument 3 of ‘Tcl_ConvertToType’ discards qualifiers from pointer target type
/usr/include/tcl-private/generic/tclDecls.h:162: note: expected ‘struct Tcl_ObjType *’ but argument is of type ‘const struct Tcl_ObjType *’
src/tcldis.c: In function ‘init_tcldis’:
src/tcldis.c:444: warning: implicit declaration of function ‘PyCapsule_Import’
src/tcldis.c:444: warning: assignment makes pointer from integer without a cast
src/tcldis.c: In function ‘tcldis_getbc’:
src/tcldis.c:171: warning: ‘tclLocal’ may be used uninitialized in this function
gcc -shared -fPIC -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro,-z,now -fno-strict-overflow -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow -Wstrict-prototypes -Wno-unused-parameter -O2 -DPY_LIBFILE='"libpython2.6.so"' _tcldis.o -o _tcldis.so -Wl,--export-dynamic -L/usr/lib64 -ltcl8.5 -lpthread -ldl -lutil -lm -lpython2.6

[genesis@localhost ~/tcldis-master]$ python
Python 2.6.6 (r266:84292, Jun 20 2019, 14:14:55) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tcldis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tcldis.py", line 7, in <module>
    import _tcldis
ImportError: ./_tcldis.so: undefined symbol: PyCapsule_Import

**Comment by aidanhs** [comment]
The pycapsule API isn't available in 2.6.

If you can't move to python2.7 via EPEL my recommendation would be to try adding in the compatibility shim at https://py3c.readthedocs.io/en/latest/capsulethunk.html

Happy to accept a PR.
